steps:
- id: docker pull
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/demo-salut:latest || exit 0
- id: docker build
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build -t gcr.io/$PROJECT_ID/demo-salut \
      --cache-from gcr.io/$PROJECT_ID/demo-salut:latest \
      .
- id: docker push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/demo-salut']
- id: Deploy to Cloud Run
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - run
  - deploy
  - demo-salut 
  - --image
  - gcr.io/$PROJECT_ID/demo-salut
  - --region
  - us-central1
  - --platform
  - managed
  - --memory
  - 512Mi
  - --cpu
  - '1'
  - --max-instances
  - '1'

images:
- gcr.io/$PROJECT_ID/demo-salut

timeout: 14400s